// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCBJUpYY-ZPDHUiLuGxDk1sVD4K0Bl2iE',
    appId: '1:430510019297:android:25884572ed299760069da0',
    messagingSenderId: '430510019297',
    projectId: 'saloon-with-admin',
    storageBucket: 'saloon-with-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEgibjgkhQUSKAHvfTHJNXxjXeoD7nww',
    appId: '1:430510019297:ios:60c3b29d87de6aae069da0',
    messagingSenderId: '430510019297',
    projectId: 'saloon-with-admin',
    storageBucket: 'saloon-with-admin.firebasestorage.app',
    androidClientId: '430510019297-mg7sc12oqmmvicusrallel16ie8m9ltf.apps.googleusercontent.com',
    iosClientId: '430510019297-7fuh5v4u1qft0t74jbp4h7jjqejdr7o3.apps.googleusercontent.com',
    iosBundleId: 'idanhair.com.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNocSyKh6MtQoFdecJXmDjAJr3_Z_1c3U',
    appId: '1:430510019297:web:11b8ae9b1466eb54069da0',
    messagingSenderId: '430510019297',
    projectId: 'saloon-with-admin',
    authDomain: 'saloon-with-admin.firebaseapp.com',
    storageBucket: 'saloon-with-admin.firebasestorage.app',
  );

}